import { Item } from "./types";

export const items: Item[] = [
  {
    id: 1,
    title: "Product 1",
    description: "Description for Product 1",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 9,
  },
  {
    id: 2,
    title: "Product 2",
    description: "Description for Product 2",
    tag: ["New"],
    price: 6.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 10,
  },
  {
    id: 3,
    title: "Product 3",
    description: "Description for Product 3",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 4,
    title: "Product 4",
    description: "Description for Product 4",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 8,
  },
  {
    id: 5,
    title: "Product 5",
    description: "Description for Product 5",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: 6,
    title: "Product 6",
    description: "Description for Product 6",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 4,
  },
  {
    id: 7,
    title: "Product 7",
    description: "Description for Product 7",
    tag: ["New"],
    price: 8.99,
    category: "Category B",
    pic: "/product3.jpg",
    stock: 0,
  },
  {
    id: 8,
    title: "Product 8",
    description: "Description for Product 8",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: 9,
    title: "Product 9",
    description: "Description for Product 9",
    tag: ["New"],
    price: 11.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 22,
  },
  {
    id: 10,
    title: "Product 10",
    description: "Description for Product 10",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 11,
    title: "Product 11",
    description: "Description for Product 11",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: 12,
    title: "Product 12",
    description: "Description for Product 12",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/product3.jpg",
    stock: 2,
  },
  {
    id: 13,
    title: "Product 13",
    description: "Description for Product 13",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 8,
  },
  {
    id: 14,
    title: "Product 14",
    description: "Description for Product 14",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 8,
  },
  {
    id: 15,
    title: "Product 15",
    description: "Test",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: 16,
    title: "Product 16",
    description: "Description for Product 16",
    tag: ["New"],
    price: 6.99,
    category: "Category B",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 17,
    title: "Product 17",
    description: "Description for Product 17",
    tag: ["New"],
    price: 3.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 8,
  },
  {
    id: 18,
    title: "Product 18",
    description: "Description for Product 18",
    tag: ["New"],
    price: 4.99,
    category: "Category A",
    pic: "/product2.jpg",
    stock: 1,
  },
  {
    id: 19,
    title: "Product 19",
    description: "Description for Product 19",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 20,
    title: "Product 20",
    description: "Description for Product 20",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 21,
    title: "Product 21",
    description: "Description for Product 21",
    tag: ["New"],
    price: 2.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 1,
  },
  {
    id: 22,
    title: "Product 22",
    description: "Description for Product 22",
    tag: ["New"],
    price: 4.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 3,
  },
  {
    id: 23,
    title: "Product 23",
    description: "Description for Product 23",
    tag: ["New"],
    price: 11.99,
    category: "Category A",
    pic: "/product3.jpg",
    stock: 8,
  },
  {
    id: 24,
    title: "Product 24",
    description: "Description for Product 24",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: 25,
    title: "Product 25",
    description: "Description for Product 25",
    tag: ["New"],
    price: 7.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 4,
  },
];
