import { Item } from "./types";

export const items: Item[] = [
  {
    id: "01",
    title: "Product 1",
    description: "Description for Product 1",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/01.webp",
    stock: 9,
  },
  {
    id: "02",
    title: "Product 2",
    description: "Description for Product 2",
    tag: ["New"],
    price: 6.99,
    category: "Category B",
    pic: "/02.webp",
    stock: 10,
  },
  {
    id: "03",
    title: "Product 3",
    description: "Description for Product 3",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/03.webp",
    stock: 8,
  },
  {
    id: "04",
    title: "Product 4",
    description: "Description for Product 4",
    tag: ["New"],
    price: 9.99,
    category: "Category A",
    pic: "/04.webp",
    stock: 8,
  },
  {
    id: "05",
    title: "Product 5",
    description: "Description for Product 5",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/05.webp",
    stock: 8,
  },
  {
    id: "06",
    title: "Product 6",
    description: "Description for Product 6",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/06.webp",
    stock: 4,
  },
  {
    id: "07",
    title: "Product 7",
    description: "Description for Product 7",
    tag: ["New"],
    price: 8.99,
    category: "Category B",
    pic: "/07.webp",
    stock: 0,
  },
  {
    id: "08",
    title: "Product 8",
    description: "Description for Product 8",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/08.webp",
    stock: 8,
  },
  {
    id: "09",
    title: "Product 9",
    description: "Description for Product 9",
    tag: ["New"],
    price: 11.99,
    category: "Category A",
    pic: "/09.webp",
    stock: 22,
  },
  {
    id: "10",
    title: "Product 10",
    description: "Description for Product 10",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/10.webp",
    stock: 8,
  },
  {
    id: "11",
    title: "Product 11",
    description: "Description for Product 11",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/11.webp",
    stock: 8,
  },
  {
    id: "12",
    title: "Product 12",
    description: "Description for Product 12",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/12.webp",
    stock: 2,
  },
  {
    id: "13",
    title: "Product 13",
    description: "Description for Product 13",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/13.webp",
    stock: 8,
  },
  {
    id: "14",
    title: "Product 14",
    description: "Description for Product 14",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/14.webp",
    stock: 8,
  },
  {
    id: "15",
    title: "Product 15",
    description: "Test",
    tag: ["New"],
    price: 3.99,
    category: "Category B",
    pic: "/15.webp",
    stock: 8,
  },
  {
    id: "16",
    title: "Product 16",
    description: "Description for Product 16",
    tag: ["New"],
    price: 6.99,
    category: "Category B",
    pic: "/16.webp",
    stock: 8,
  },
  {
    id: "17",
    title: "Product 17",
    description: "Description for Product 17",
    tag: ["New"],
    price: 3.99,
    category: "Category A",
    pic: "/17.webp",
    stock: 8,
  },
  {
    id: "18",
    title: "Product 18",
    description: "Description for Product 18",
    tag: ["New"],
    price: 4.99,
    category: "Category A",
    pic: "/18.webp",
    stock: 1,
  },
  {
    id: "19",
    title: "Product 19",
    description: "Description for Product 19",
    tag: ["New"],
    price: 5.99,
    category: "Category A",
    pic: "/19.webp",
    stock: 8,
  },
  {
    id: "20",
    title: "Product 20",
    description: "Description for Product 20",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/20.webp",
    stock: 8,
  },
  {
    id: "21",
    title: "Product 21",
    description: "Description for Product 21",
    tag: ["New"],
    price: 2.99,
    category: "Category A",
    pic: "/21.webp",
    stock: 1,
  },
  {
    id: "22",
    title: "Product 22",
    description: "Description for Product 22",
    tag: ["New"],
    price: 4.99,
    category: "Category B",
    pic: "/22.webp",
    stock: 3,
  },
  {
    id: "23",
    title: "Product 23",
    description: "Description for Product 23",
    tag: ["New"],
    price: 11.99,
    category: "Category A",
    pic: "/product1.jpg",
    stock: 8,
  },
  {
    id: "24",
    title: "Product 24",
    description: "Description for Product 24",
    tag: ["New"],
    price: 5.99,
    category: "Category B",
    pic: "/product2.jpg",
    stock: 8,
  },
  {
    id: "25",
    title: "Product 25",
    description: "Description for Product 25",
    tag: ["New"],
    price: 7.99,
    category: "Category A",
    pic: "/product3.jpg",
    stock: 4,
  },
];
